// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureActiveDisplay() {
  return window['go']['main']['App']['CaptureActiveDisplay']();
}

export function CaptureFullscreen() {
  return window['go']['main']['App']['CaptureFullscreen']();
}

export function CheckAccessibilityPermission() {
  return window['go']['main']['App']['CheckAccessibilityPermission']();
}

export function CheckScreenRecordingPermission() {
  return window['go']['main']['App']['CheckScreenRecordingPermission']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function GenerateFilename(arg1) {
  return window['go']['main']['App']['GenerateFilename'](arg1);
}

export function GetDisplayInfo() {
  return window['go']['main']['App']['GetDisplayInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function PauseHotkeys() {
  return window['go']['main']['App']['PauseHotkeys']();
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function RequestScreenRecordingPermission() {
  return window['go']['main']['App']['RequestScreenRecordingPermission']();
}

export function ResumeHotkeys() {
  return window['go']['main']['App']['ResumeHotkeys']();
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
