// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {version} from '../models';
import {upload} from '../models';

export function AuthGetCurrentUser():Promise<model.User>;

export function AuthHandleCallback(arg1:string):Promise<model.User>;

export function AuthIsLoggedIn():Promise<boolean>;

export function AuthLogout():Promise<void>;

export function AuthStartLogin():Promise<string>;

export function CaptureActiveDisplay():Promise<model.CaptureResult>;

export function CaptureFullscreen():Promise<model.CaptureResult>;

export function CheckAccessibilityPermission():Promise<boolean>;

export function CheckScreenRecordingPermission():Promise<boolean>;

export function CopyImageToClipboard(arg1:Array<number>):Promise<void>;

export function GenerateFilename(arg1:string):Promise<string>;

export function GetDisplayInfo():Promise<Array<model.DisplayInfo>>;

export function GetSettings():Promise<model.Settings>;

export function GetVersion():Promise<version.Info>;

export function IsUploadConfigured():Promise<boolean>;

export function OpenImageDialog():Promise<string>;

export function OpenSaveDialog(arg1:string):Promise<string>;

export function PauseHotkeys():Promise<void>;

export function ReadImageFile(arg1:string):Promise<string>;

export function RequestAccessibilityPermission():Promise<void>;

export function RequestScreenRecordingPermission():Promise<void>;

export function ResumeHotkeys():Promise<void>;

export function SaveImage(arg1:model.SaveOptions,arg2:Array<number>):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UploadComplete(arg1:string):Promise<upload.CompleteResponse>;

export function UploadInit(arg1:string,arg2:number,arg3:string):Promise<upload.InitResponse>;
